### ISSUE TITLE
ImportError: Could not import PIL.Image. The use of `array_to_img` requires PIL.

### ISSUE THREAD

**Issue by li-xunhuan** [boozyguo/mosaic#3]
```
 python .\mosaic_porngraphic_cnn_demo.py .\data\test\22.jpg
Using TensorFlow backend.

Mosaic: detect porngraghic
=====================================
2018-08-20 14:05:13.448988: I T:\src\github\tensorflow\tensorflow\core\platform\cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
loading weights..........
load OK!

Try to Predict input images:
=====================================
Traceback (most recent call last):
  File ".\mosaic_porngraphic_cnn_demo.py", line 69, in <module>
    re_img = load_img(input_image_path)  # this is a jpg image
  File "E:\Python\Python36\lib\site-packages\keras_preprocessing\image.py", line 493, in load_img
    raise ImportError('Could not import PIL.Image. '
ImportError: Could not import PIL.Image. The use of `array_to_img` requires PIL.
```

**Comment by boozyguo** [comment]
Please run:
   sudo apt install python-pip
   pip install Image
